/**
 * Fungsi murni presentasi tagihan — dipakai TagihanTab (Penagihan).
 *
 * Diekstraksi dari TagihanTab.tsx agar bisa dites unit tanpa React/IndexedDB.
 * Semua fungsi di sini tidak boleh punya dependensi pada db/hooks.
 */
import type { Payment, Settings, Student } from "../db/types";
import { formatRupiah, monthLabel } from "./format";
import { ageBucket, invoiceAgeDays } from "./finance";
import type { BillingTone } from "./waBilling";

// ── Asal invoice ───────────────────────────────────────────────────────

export type InvoiceOrigin = "package" | "monthly" | "report" | "manual";
export type InvoiceOriginFilter = "semua" | InvoiceOrigin;

export function invoiceOriginOf(payment: Payment, report?: { billingMode?: string; autoGenerated?: boolean }): InvoiceOrigin {
  if (report?.billingMode === "session_count") return "package";
  if (report?.autoGenerated) return "monthly";
  if (payment.reportId) return "report";
  if (payment.source === "auto") return "monthly";
  return "manual";
}

export const INVOICE_ORIGIN_LABEL: Record<InvoiceOrigin, string> = {
  package: "Paket",
  monthly: "Bulanan/Tutup Buku",
  report: "Laporan Perkembangan",
  manual: "Manual",
};

export const INVOICE_ORIGIN_CLASS: Record<InvoiceOrigin, string> = {
  package: "bg-indigo-100 text-indigo-700",
  monthly: "bg-sky-100 text-sky-700",
  report: "bg-blue-50 text-blue-700",
  manual: "bg-gray-100 text-gray-600",
};

// ── Nada pesan WA mengikuti umur piutang ──────────────────────────────
// normal → gentle (>30 hari) → firm (>60 hari).

export function toneForPayment(payment: Pick<Payment, "periodEnd" | "month">): BillingTone {
  const bucket = ageBucket(invoiceAgeDays(payment));
  return bucket === ">60" ? "firm" : bucket === "31-60" ? "gentle" : "normal";
}

// ── Teks WA tagihan manual (tanpa sesi) ───────────────────────────────

export function buildManualBillingText(student: Student, payment: Payment, settings: Settings): string {
  const bank = settings.bankAccounts;
  const lines = [
    `NAMA MURID: ${student.name}`,
    "",
    monthLabel(payment.month),
    "",
    "TAGIHAN MANUAL (TANPA SESI)",
    `Total Tagihan — ${formatRupiah(payment.totalCost)}`,
  ];

  if (bank && (bank.bca || bank.cimb || bank.bri || bank.mandiri || bank.bsi || bank.ewallet)) {
    lines.push("");
    if (bank.bca) lines.push(`BCA ${bank.bca}`);
    if (bank.cimb) lines.push(`CIMB ${bank.cimb}`);
    if (bank.bri) lines.push(`BRI ${bank.bri}`);
    if (bank.mandiri) lines.push(`Mandiri ${bank.mandiri}`);
    if (bank.bsi) lines.push(`BSI ${bank.bsi}`);
    if (bank.ewallet) lines.push(`E-wallet ${bank.ewallet}`);
    if (bank.accountName) lines.push(`a.n. ${bank.accountName}`);
  }

  lines.push("", "Thank you 😇", settings.tutorProfile?.name || "Ko Lui");
  return lines.join("\n");
}

// ── Pagination PDF rekap tagihan ──────────────────────────────────────

export const ITEMS_PER_PDF_PAGE = 5;

/** Pecah daftar payment menjadi halaman PDF berukuran tetap. */
export function groupPdfPages(payments: readonly Payment[], perPage = ITEMS_PER_PDF_PAGE): Payment[][] {
  const groups: Payment[][] = [];
  for (let i = 0; i < payments.length; i += perPage) {
    groups.push(payments.slice(i, i + perPage));
  }
  return groups;
}

/** Kelas Tailwind pill status lunas/belum. */
export function statusPillClass(paid: boolean): string {
  return `text-[11px] font-semibold px-2 py-0.5 rounded-full ${paid ? "text-green-700 bg-green-100" : "text-amber-700 bg-amber-100"}`;
}
