import pkg from "../../package.json";

export const APP_VERSION = `v${pkg.version}`;

export interface ChangelogEntry {
  version: string;
  date: string;
  title: string;
  items: string[];
}

export const CHANGELOG: ChangelogEntry[] = [
{
    version: "v1.57.0",
    date: "2026-08-28",
    title: "Laporan Bulanan Dipecah Jadi Modul Kecil (Refactor)",
    items: [
      "Halaman Laporan Bulanan dipecah dari 2.466 menjadi ~1.900 baris: helpers murni, editor rencana depan, builder tema kustom, hook export, dan hook generasi AI dipindah ke folder `screens/monthlyReport/`",
      "Seluruh logika AI (narasi, ringkasan, fallback gratis) kini terkumpul di satu modul `useReportGeneration.ts` — mudah dibaca dan murah token",
      "Perilaku tidak berubah — hanya restrukturisasi file; seluruh 326 unit test tetap hijau dan build produksi lolos tanpa migrasi schema",
    ],
  },
{
    version: "v1.56.0",
    date: "2026-08-28",
    title: "Prediksi vs Nilai Aktual di Laporan — Konteks Ujian Jelas",
    items: [
      "Setiap sesi yang punya nilai akurat kini menampilkan chip 'Ujian: prediksi → aktual' — ujian merujuk topik spesifik (mis. Paper 2), bukan mapel generik",
      "Layout Rapor Style & Progress Bar menampilkan tabel 'Prediksi vs Nilai Aktual' (Tanggal · Ujian · Prediksi · Aktual · Δ) untuk melihat akurasi prediksi sekilas",
      "AI kini menerima nilai akhir & refleksi per sesi, sehingga narasi bisa menyebut perbandingan prediksi vs aktual secara natural",
    ],
  },
{
    version: "v1.55.0",
    date: "2026-08-28",
    title: "Tren Fokus Bulan-ke-Bulan di Laporan",
    items: [
      "Laporan kini membandingkan rata-rata fokus periode ini terhadap laporan periode sebelumnya (MoM), tampil sebagai badge '▲ 6 → 7 vs periode lalu' di layout Dashboard, Ringkasan Eksekutif, dan Infografis",
      "Ringkasan AI memakai rata-rata fokus periode sebelumnya sebagai konteks, sehingga narasi bisa menyebut perkembangan antar periode secara natural",
      "Perhitungan rata-rata engagement diekstrak jadi helper bersama (sessionEngagementScore, averageEngagement) — konsisten lintas layar",
    ],
  },
{
    version: "v1.54.0",
    date: "2026-08-28",
    title: "AI Laporan Hemat Token — Tidak Membaca Ulang Sesi yang Sama",
    items: [
      "Perkuat Narasi AI kini hanya mengirim sesi yang berubah (shortNote/mood/topik/nilai berubah atau narasi masih kosong) — narasi lain, termasuk edit manual tutor, dipertahankan",
      "Perkuat Teks AI (ringkasan) otomatis dilewati bila tidak ada perubahan sesi sejak ringkasan terakhir dibuat",
      "Biaya ditampilkan sesuai jumlah sesi yang benar-benar dikirim, plus opsi 'Tulis ulang paksa' bila ingin regenerasi penuh",
      "Fingerprint konten (FNV-1a non-kriptografis) disimpan sebagai field non-indexed — tanpa migrasi schema dan tetap kompatibel dengan backup lama",
    ],
  },
{
    version: "v1.53.0",
    date: "2026-08-28",
    title: "Daftar Murid Lebih Kuat dan Aman",
    items: [
      "Kartu murid kini menampilkan avatar berwarna konsisten dengan kalender Home, plus badge peringatan untuk follow-up tertunda dan tagihan belum dibayar",
      "Nonaktifkan murid kini memperingatkan bila masih ada jadwal mendatang; nama murid nonaktif tetap tampil di kalender Home",
      "Hapus murid kini menampilkan ringkasan data yang ikut terhapus (sesi, laporan, tagihan, follow-up, nilai rapor, IA/EE, catatan) plus opsi nonaktifkan saja",
      "Semua aksi murid (tambah/edit/nonaktifkan/aktifkan/hapus) kini memberi notifikasi toast; PIN bisa dikonfirmasi dengan tombol Enter",
      "Empty state dan pencarian yang lebih jelas, plus panduan membuat jadwal pertama setelah menambah murid",
    ],
  },
  {
    version: "v1.52.0",
    date: "2026-08-28",
    title: "Laporan Lama Tanpa Status Tidak Lagi Menyembunyikan Sesi",
    items: [
      "Snapshot laporan yang dibuat sebelum kolom status ada kini tidak lagi otomatis 'mengunci' sesi laporan tetangganya setelah restore — selama laporan itu tidak punya invoice yang dibayar atau ditagih manual, snapshotnya boleh dimuat ulang tanpa menyembunyikan sesi berikutnya",
      "Laporan lama tanpa status yang justru sudah punya invoice (dibayar atau manual) tetap mengunci sesinya agar tidak tertagih dua kali",
      "Restore backup legacy mengembalikan laporan tanpa status sesuai aslinya alih-alih memaksakan 'confirmed', sehingga cakupan sesi terhitung ulang secara akurat",
    ],
  },
  {
    version: "v1.51.2",
    date: "2026-08-27",
    title: "Audit Laporan dan Katalog Lebih Stabil",
    items: [
      "Audit seluruh layout laporan kini menunggu pratinjau selesai diperbarui, sehingga perubahan desain dan rebalance halaman tidak lagi membuat pemeriksaan gagal sesaat",
      "Katalog screenshot diperbarui, termasuk halaman Catatan Belajar, tanpa pengingat backup yang menutupi pratinjau fitur",
    ],
  },
  {
    version: "v1.51.1",
    date: "2026-08-27",
    title: "Laporan 3:4 Tidak Lagi Memotong Catatan Sesi",
    items: [
      "Sesi di laporan bulanan otomatis dipindah ke halaman berikutnya bila catatan panjang melebihi kotak 3:4 — narasi, topik, dan ringkasan tidak terpotong lagi",
      "Halaman laporan rasio 3:4 kini diisi penuh oleh kartu tema (tanpa area putih kosong di bawah)",
      "Halaman yang tetap terlalu tinggi (cover, atau halaman terakhir dengan ringkasan panjang) dibiarkan mengikuti tinggi isinya alih-alih memotong konten",
      "Prinsip 'sesi per halaman' tetap berlaku: angka itu target awal, bukan batas kaku",
    ],
  },
  {
    version: "v1.51.0",
    date: "2026-08-27",
    title: "Laporan & Penagihan Makin Jelas",
    items: [
      "Subtab Penagihan: Siap Ditagih, Belum Dibayar, Lunas, Semua + filter asal terpisah (Bulanan, Paket, Laporan, Manual)",
      "Antrean paket diberi banner 'Lintas bulan — tidak dipengaruhi pilihan Bulan Keuangan'",
      "Laporan final punya CTA 'Buat Tagihan dari Sesi Ini' dan status 'Sudah dibagikan'",
      "Invoice menampilkan Asal, Periode sesi, Bulan tagihan, status laporan, dan CTA buka/lengkapi laporan",
      "Pengeluaran bisa diedit",
      "Ringkasan Keuangan menampilkan antrean 'Perlu tindakan' paling atas",
    ],
  },
  {
    version: "v1.49.1",
    date: "2026-08-23",
    title: "Pesan WA & Poster Lebih Rapi",
    items: [
      "Pesan WA tagihan murid paket menampilkan Total Pertemuan (bukan jam), tanpa ikon kalender dan tanpa detail jam les",
      "Pesan WA murid bulanan mengganti tanggal berulang dengan ikon penanda yang lebih rapi",
      "Laporan/poster murid paket tidak lagi menampilkan durasi per sesi",
    ],
  },
  {
    version: "v1.49.0",
    date: "2026-08-23",
    title: "Tarif per Pertemuan untuk Murid Paket",
    items: [
      "Murid dengan siklus 'Paket per N pertemuan' kini ditagih tarif flat per pertemuan, bukan per jam",
      "Sesi lama yang belum ditagih otomatis dihitung ulang saat murid beralih (atau disimpan ulang) ke paket pertemuan",
      "Label tarif di profil menyesuaikan menjadi 'per Pertemuan' untuk murid paket",
    ],
  },
  {
    version: "v1.48.7",
    date: "2026-08-23",
    title: "Sesi Paket Historis Tidak Lagi Tersembunyi",
    items: [
      "Antrean paket dan halaman Laporan kini memakai aturan cakupan sesi yang sama",
      "Rekam laporan lama tanpa status dan tanpa invoice tidak lagi mengurangi sesi paket saat murid berpindah dari bulanan ke pertemuan",
      "Laporan yang dikonfirmasi secara eksplisit atau sudah memiliki invoice tetap mengunci sesi agar tidak dapat ditagih dua kali",
    ],
  },
  {
    version: "v1.48.6",
    date: "2026-08-23",
    title: "Laporan Paket Belum Lunas Mengikuti Sesi Terlambat",
    items: [
      "Laporan paket dengan tagihan otomatis yang masih belum dibayar kini membaca sesi selesai terbaru, termasuk sesi historis yang baru dicatat",
      "Sesi Mei yang terlambat dicatat dapat melengkapi laporan dari 8/10 menjadi 10/10, lalu memperbarui tagihan otomatis yang sama",
      "Invoice yang sudah lunas atau nominalnya diedit manual tetap terkunci agar catatan keuangan tidak berubah",
    ],
  },
  {
    version: "v1.48.5",
    date: "2026-08-23",
    title: "Laporan Paket Selalu Membaca Sesi Terbaru",
    items: [
      "Antrean laporan paket memperbarui batas tanggal setiap kali data sesi berubah, sehingga sesi di bulan berikutnya tetap masuk meski halaman Laporan sudah lama terbuka",
      "Label draft paket kini menampilkan progres sesi langsung, misalnya 10/10 sesi, bukan angka snapshot lama",
      "Laporan dan invoice yang sudah disahkan tetap memakai snapshot sesi yang terkunci",
    ],
  },
  {
    version: "v1.48.4",
    date: "2026-08-23",
    title: "Laporan Paket Mengikuti Sesi Terbaru",
    items: [
      "Draft laporan paket kini membaca sesi billable terbaru, sehingga progres 8/10 otomatis menjadi 10/10 setelah sesi historis dicatat",
      "Perubahan kuota paket di profil murid langsung tersinkron di layar Laporan tanpa memuat ulang halaman",
      "Saat paket lengkap diterbitkan, draft FIFO yang sudah ada diperpanjang dan dipakai ulang agar isi laporan tidak tertinggal",
    ],
  },
  {
    version: "v1.48.3",
    date: "2026-08-21",
    title: "Bukti Sesi Bisa Dilengkapi & Penghapusan Lebih Jelas",
    items: [
      "Foto sesi kini dapat ditambahkan, diganti, atau dihapus dari Edit Catatan Sesi lewat Kamera atau Galeri",
      "Penghapusan sesi dapat diakses dari editor; aplikasi menjelaskan kebutuhan PIN Keuangan dan mengarahkan ke Pengaturan bila PIN belum dibuat",
      "Ikon edit di riwayat sesi tidak lagi ikut membuka detail sesi di belakang editor",
    ],
  },
  {
    version: "v1.48.2",
    date: "2026-08-20",
    title: "Ekspor Laporan Lebih Ringkas untuk WhatsApp",
    items: [
      "Pilih 2, 3, 4, atau 6 sesi per halaman langsung dari laporan bulanan",
      "Ekspor JPG/PNG memakai rasio potret 3:4 agar halaman lebih praktis dibagikan lewat WhatsApp",
      "PDF otomatis memakai tinggi halaman penuh supaya seluruh isi laporan tetap terlihat",
    ],
  },
  {
    version: "v1.48.1",
    date: "2026-08-20",
    title: "Ekspor Laporan WYSIWYG — foto lebih utuh dan tajam",
    items: [
      "JPG, PNG, dan PDF kini memakai komposisi pratinjau yang terlihat, sehingga rasio kotak foto tidak berubah saat diekspor",
      "Foto laporan memakai resolusi tersimpan tanpa center-crop ulang ke 360 px",
      "Ekspor menunggu semua gambar siap dan menyesuaikan densitas raster agar hasil tetap tajam di layar ponsel maupun desktop",
    ],
  },
  {
    version: "v1.48.0",
    date: "2026-08-20",
    title: "Keuangan Lebih Ringan — tab dipecah, lazy-load, dan UX penagihan lebih jelas",
    items: [
      "Layar Keuangan dipecah per tab (Ringkasan, Tagihan, Pengeluaran, Audit) + invoice modal terpisah",
      "Data grafik/audit/paket dimuat lazy per tab sehingga halaman lebih ringan",
      "Ringkasan: kartu hero laba, satu grafik Kas vs Pengeluaran 3/6/12 bulan, forecast tidak dobel, tab Murid digabung",
      "Tab Tagihan punya badge 'perlu tindakan' dan tombol Daftar Tagihan (semua link WA tagihan belum lunas)",
      "window.confirm diganti bottom-sheet ConfirmSheet; progress paket memakai ActivityRing",
      "Helper keuangan sumExpensesByCategory + formatIdrNumber; preview tutup bulan satu sumber (computeMonthBills)",
    ],
  },
  {
    version: "v1.47.0",
    date: "2026-08-20",
    title: "Follow-up Nilai Prediksi → Aktual, Topik Multi, dan IA/EE/PP Lebih Jelas",
    items: [
      "Prediksi Nilai kembali hadir di wizard Catat Sesi (Step 5) dan diteruskan ke AI draft",
      "Edit Catatan Sesi kini punya Nilai Akhir; refleksi wajib diisi bila nilai akhir lebih rendah dari prediksi",
      "Detail sesi menampilkan chip Prediksi / Nilai Akhir / Refleksi",
      "Pemilihan topik mendukung banyak topik (chip + pemisah ;) dan bisa search lagi setelah memilih",
      "IA/EE/PP diperjelas: tipe PP tersedia, deskripsi tiap tipe, tracker terbuka untuk IB MYP",
      "Query sesi memakai index date/studentId (bukan full-table filter) agar lebih ringan",
      "Default rekening bank dikosongkan, a11y stateful ditambah, CSV export tanpa menahan seluruh Blob",
    ],
  },
  {
    version: "v1.46.0",
    date: "2026-08-19",
    title: "Sederhanakan Catatan Belajar & Nilai — otomatis dari sesi, hapus fitur rancu",
    items: [
      "Catatan Belajar kini terisi otomatis dari 5 sesi terakhir (topik, catatan terakhir, perhatian, rencana) — input manual jadi opsional",
      "Tombol Otomatis untuk merakit ulang catatan dari sesi terakhir; AI Perkuat tetap tersedia",
      "Input Nilai Rapor manual dihapus; tab Nilai diganti Progres yang fokus ke perkembangan les",
      "Analisis AI di Riwayat Sesi dihapus karena tumpang tindih dengan Progres",
      "Prediksi Nilai per sesi dihapus dari input, tampilan sesi, dan laporan",
    ],
  },
  {
    version: "v1.45.0",
    date: "2026-08-19",
    title: "Laporan Bulanan Lebih Jelas — 4 sesi/halaman, teks gratis, dan alur AI setelah laporan dibuat",
    items: [
      "Detail murid: tombol Tagihan Bulanan ganda dihapus untuk siklus Bulanan — laporan bulanan diakses lewat Lihat Laporan, pembayaran dicek di Keuangan",
      "Tombol AI di laporan hanya muncul setelah laporan dibuat; namanya kini Perkuat Narasi AI dan Perkuat Teks AI",
      "Sahkan diperjelas menjadi Sahkan & Terbitkan Tagihan dengan keterangan: belum mengirim ke orang tua dan belum menandai dibayar",
      "PDF/JPG laporan kini 4 sesi per halaman (preview dan export konsisten)",
      "Narasi sesi dan teks laporan bisa di-generate otomatis gratis dari data sesi; AI menjadi opsi perkuat",
    ],
  },
  {
    version: "v1.44.0",
    date: "2026-08-19",
    title: "Wizard Catatan Lebih Kuat — rangkum lokal, pratinjau AI, dan Catatan Belajar markdown",
    items: [
      "Tombol Rangkum Cepat di Step Catatan merangkai mapel, topik, mood, engagement, perilaku, needsWork, sesi lalu, dan follow-up jadi draft 2–4 kalimat gratis tanpa AI",
      "Hasil Draft AI tidak lagi langsung menimpa catatan — muncul sebagai Usulan AI dengan Terima/Tolak dan tombol Kembalikan ke teks awal",
      "Modal Draft AI kini punya pilihan gaya Rapikan/Perluas/Ringkas, dan follow-up sesi lalu ikut dikirim ke DeepSeek",
      "Chips saran 1-klik tampil sebelum mengetik: sesi lalu, follow-up, dan area perlu perhatian",
      "Catatan Belajar (/catatan) dan kartu catatan di detail murid kini punya pratinjau markdown; hasil Perkuat AI bisa di-undo",
    ],
  },
  {
    version: "v1.43.0",
    date: "2026-08-19",
    title: "Foto laporan lebih besar & AI DeepSeek Flash hemat",
    items: [
      "Foto absensi di semua layout laporan diperbesar — thumbnail 30–48px naik ke 56–72px dan foto utama ikut diperbesar agar nyaman dilihat di PDF/JPG",
      "Export PDF/JPG kini dirender pada lebar A4 tetap (794px) terpisah dari preview HP, sehingga hasil export tidak lagi mengecil mengikuti lebar layar",
      "Isi textbox Catatan Singkat dikirim sebagai draftText dan menjadi bahan utama saat ✨ Draft AI dipanggil — AI memoles tulisan tutor, bukan menulis dari nol",
      "Semua panggilan AI dikunci ke deepseek-v4-flash; pilihan model pro/custom dinonaktifkan di Pengaturan",
      "Biaya AI dipangkas: thinking mode dimatikan, max_tokens dibatasi per jenis panggilan, dan estimasi memakai tarif flash off-peak ($0.22 input / $0.66 output per 1M token)",
    ],
  },
  {
    version: "v1.42.1",
    date: "2026-08-14",
    title: "Perbaikan PWA — hilangkan 'Failed to fetch dynamically imported module' setelah update",
    items: [
      "Service worker kini autoUpdate: SW baru langsung skipWaiting + clientsClaim lalu reload, sehingga index.html basi yang mereferensikan chunk lama tidak lagi memicu gagal muat modul",
      "Banner 'Versi baru tersedia / Muat Ulang' dihapus — update kini diterapkan otomatis tanpa konfirmasi",
    ],
  },
  {
    version: "v1.42.0",
    date: "2026-08-14",
    title: "Laporan Bulanan Seragam — semangat, keseriusan, topik, durasi & tanda tangan di semua layout",
    items: [
      "Blok meta seragam per sesi (SessionMeta) kini tampil di semua layout: badge semangat (mood) + label keseriusan (Sangat Baik/Baik/Cukup/Kurang Fokus/Perlu Perhatian) tanpa angka mentah",
      "Topik spesifik, durasi & jam, prediksi nilai, area 'perlu perhatian', dan tanda tangan murid kini menjadi field terstruktur dan selalu tampil di setiap entri sesi",
      "Tanda tangan murid dicetak langsung di tiap entri sesi (menggantikan halaman 'Rekap Tanda Tangan' terpisah)",
      "Layout Rapor Style menghapus kolom angka 'Engage' dan menampilkan meta standar di kolom catatan",
    ],
  },
  {
    version: "v1.41.0",
    date: "2026-08-11",
    title: "Penguatan Keuangan & Laporan — invoice aman, laporan susulan, dan UI mobile",
    items: [
      "Tutup dan buka bulan kini idempoten; tagihan manual tidak dihitung ganda dan invoice laporan lama yang hilang dipulihkan otomatis",
      "Invoice manual atau yang sudah lunas tetap utuh; sesi terlambat diterbitkan sebagai laporan susulan dengan periode dan tagihan terpisah",
      "Pembuatan serta pengesahan laporan kini atomik dengan perlindungan overlap, double-click, dan perubahan data lintas tab",
      "Mode Jumlah memakai tepat N sesi secara kronologis untuk tampilan, penyimpanan, dan estimasi biaya AI",
      "AI Keuangan selalu meminta persetujuan biaya dan hasilnya terikat ke bulan aktif agar tidak menampilkan analisis lama",
      "Restore backup lama menormalisasi periode laporan secara aman tanpa mengubah nominal atau status pembayaran",
      "Tampilan Keuangan, invoice, dan laporan diperbaiki untuk layar 320 px serta membedakan tagihan Manual, Laporan, dan Susulan",
      "Regresi lifecycle keuangan, invoice, backup, scope laporan, dan insight AI kini dilindungi oleh rangkaian test baru",
    ],
  },
  {
    version: "v1.40.0",
    date: "2026-08-08",
    title: "Keuangan Unified + AI Insight — semua tagihan dari laporan, anomali & rekomendasi otomatis",
    items: [
      "Tutup Buku sekarang bikin laporan otomatis per murid (periode satu bulan penuh) + langsung sahkan — tidak ada lagi tagihan 'bulanan' terpisah",
      "Semua tagihan bersumber dari laporan — filter Tagihan: Semua / Bulan Penuh / Periode Rekap",
      "Buka Kembali: un-sahkan laporan otomatis, balik ke draft, hapus tagihan UNPAID",
      "Ringkasan, Tagihan, Pengeluaran, Audit, Murid: seluruh tab diperkuat dengan info laporan & periode",
      "AI Insight di Ringkasan: ✨ Analisis AI — deteksi anomali (⚠️/✅/ℹ️) & rekomendasi bisnis (💡) dari data bulan ini + 3 bulan sebelumnya",
      "AI membaca potensi, tagihan, piutang, laba, pengeluaran, pendapatan per murid, proyeksi — kasih insight yang langsung bisa ditindaklanjuti",
    ],
  },
  {
    version: "v1.39.0",
    date: "2026-08-08",
    title: "Status Draft/Sah Laporan: rekap coba-coba dulu, sahkan kalau sudah yakin",
    items: [
      "Buat Laporan sekarang jadi draft — tanggal belum terkunci & tagihan belum terbit",
      "Tombol Sahkan setelah review: kunci tanggal + terbitkan tagihan otomatis di Keuangan",
      "Tombol Batalkan Draft: hapus laporan percobaan tanpa jejak",
      "Draft tidak memblokir rekap lain (overlap guard hanya mengecek laporan yang sudah sah)",
      "Tutup bulan tidak mengecualikan sesi draft — hanya sesi laporan sah yang dilindungi",
      "Laporan lama (sebelum v1.39) otomatis dianggap sah (status confirmed)",
    ],
  },
  {
    version: "v1.38.0",
    date: "2026-08-08",
    title: "Laporan Periode Bebas: Rekap N Pertemuan / Rentang Tanggal + Tagihan per Laporan",
    items: [
      "Laporan bisa digenerate dari N pertemuan terakhir yang belum direkap atau rentang tanggal pilihan — tidak wajib tutup buku tiap bulan",
      "Tanggal yang sudah pernah direkap atau masuk bulan yang sudah tutup buku tidak bisa digenerate lagi (anti rekap ganda, lengkap dengan alasan)",
      "Setiap laporan otomatis menerbitkan tagihan; status Lunas/Belum + nominal tampil di halaman Keuangan per periode dan di layar laporan",
      "Tagihan laporan masuk ke bulan akhir periode; kas masuk (realisasi) tetap dicatat sesuai tanggal pembayaran aktual",
      "Tutup bulan tidak menagih ulang sesi yang sudah masuk laporan — sisa sesi yang belum direkap tetap ditagih terpisah",
      "Tombol Sudah Transfer / Batalkan / ubah nominal kini berbasis id tagihan — aman walau ada lebih dari satu tagihan per murid-bulan",
      "Tagihan WA, invoice PDF, dan CSV menampilkan periode laporan (mis. 20 Januari – 3 Februari 2026)",
      "Laporan lama otomatis dianggap periode satu bulan kalender penuh (migrasi data v11)",
    ],
  },
  {
    version: "v1.37.0",
    date: "2026-08-02",
    title: "Perbaikan Audit Total: Baseline Hijau & Konsistensi Data",
    items: [
      "Lint bersih total (0 error 0 warning) dan 166 unit test lulus — CI kembali hijau",
      "Recovery PIN (PIN lama & jawaban keamanan) kini dibatasi lockout bertahap dan guard percobaan paralel",
      "Hapus sesi otomatis menyesuaikan tagihan otomatis yang belum lunas dan total laporan bulanan — tidak ada lagi piutang hantu",
      "Tutup bulan mencatat snapshot hanya tagihan yang benar-benar dibuat dan aman dipanggil berulang (double-tap)",
      "Mengubah nominal tagihan menandainya sebagai manual — tidak lagi ikut berubah saat sesi dihapus",
      "Catatan Belajar menampilkan waktu relatif yang benar (bukan selalu '+7 jam')",
      "Reset database kini menghapus semua data domain lama, termasuk catatan belajar dan pengaturan, lalu menyimpan satu jejak reset",
      "Pembaruan aplikasi tidak lagi memuat ulang paksa di tengah mengisi form — banner 'Muat Ulang' yang memutuskan",
      "Label form terhubung ke kolomnya (aksesibilitas) dan semua dialog dikenali pembaca layar",
      "Kode mati dibersihkan dan TypeScript strict mode aktif",
      "Dependency transitif DOMPurify, PostCSS, fast-uri, dan brace-expansion diperbarui ke versi patched",
      "Backup memperbaiki bug tabel Catatan Belajar yang gagal divalidasi saat restore",
    ],
  },
  {
    version: "v1.36.0",
    date: "2026-08-01",
    title: "Keuangan Terhubung & Rekonsiliasi Kas",
    items: [
      "Kas masuk dan laba kini mengikuti tanggal pembayaran aktual, bukan bulan tagihan",
      "Ringkasan memisahkan potensi sesi, tagihan terbit, tagihan terbayar, piutang, kas masuk, dan pengeluaran",
      "Grafik tren mengikuti bulan yang dipilih dan tidak lagi mengisi bulan sebelumnya dengan angka nol palsu",
      "Rekonsiliasi sesi dan tagihan menandai penyesuaian manual atau perubahan setelah tutup bulan",
      "Tab Pengeluaran kembali dengan daftar transaksi, tambah, hapus, kategori, dan total bulanan yang live",
      "Audit tahunan kini menyertakan potensi, kas masuk, piutang, pengeluaran, dan laba kas",
      "Histori keuangan tetap menampilkan nama murid nonaktif dan semua tagihan belum lunas",
    ],
  },
  {
    version: "v1.35.0",
    date: "2026-07-31",
    title: "Catatan Belajar Pintar + Wizard Simpler + Engagement Granular",
    items: [
      "Catatan Belajar sekarang ikut backup/restore — tidak hilang saat ganti perangkat",
      "Konteks sesi di halaman Catatan: chip expandable 📋 menampilkan shortNote 5 sesi terakhir per murid",
      "Tombol ✨ Ringkas: AI merangkum shortNote sesi terakhir + catatan existing → StudyNote terstruktur (Topik / PR / Kelemahan / Rencana)",
      "AI draftStudyNote() — prompt khusus untuk merangkum sesi ke catatan belajar berkelanjutan",
      "getRecentDoneSessions() — fungsi baru untuk mengambil N sesi DONE terakhir per murid",
      "Wizard Catat Sesi: Step 2 Materi — Fokus Utama + Sub-Topik digabung jadi satu combobox cari-topik (dropdown IB + bisa ketik custom)",
      "Wizard Catat Sesi: Step 4 Detail — input Topik dihapus (cukup di step 2), sekarang fokus ke Respons & Nilai",
      "Step 3 Kondisi: tambah indikator negatif ⏰ Telat (−1) dan 🚻 Sering ke toilet (−1)",
      "Rekalibrasi skor engagement: bonus positif dinerf (prepared +3→+2, focused/activeAsking/quickLearner +2→+1) — skala 5-10 kini lebih granular",
      "Fix React #310: 4 useMemo di halaman Keuangan dipindahkan sebelum early return — tidak lagi crash saat unlock PIN",
      "Step 4 Detail: Kualitas Respons Akademik dikelompokkan 3 tingkat — ✨ Pemahaman Baik / 📊 Perlu Pendalaman / ⚠️ Perlu Perhatian — dengan badge skor (+2/+1/0/−1/−2) dan deskripsi + teacher note langsung terlihat saat dipilih",
      "Halaman Keuangan: tab Pengeluaran dihapus (redundan dengan 💸 Catat di Home), tab Operasional dihapus (metrik tidak jelas + no-show tidak update)",
    ],
  },
  {
    version: "v1.34.0",
    date: "2026-07-30",
    title: "Gabung Keuangan & Analitik, Tugas → Catatan Belajar",
    items: [
      "Halaman Keuangan & Analitik digabung jadi satu — 6 tab: Ringkasan, Tagihan, Pengeluaran, Audit, Murid, Operasional",
      "Ringkasan kini punya BarChart, LineChart, DonutChart & forecast — wawasan finansial langsung di satu tempat",
      "Fitur Tugas/PR dihapus total — diganti Catatan Belajar per murid (auto-save textarea)",
      "Catatan Belajar bisa diedit dari halaman /catatan (daftar semua murid + search) dan dari StudentDetail",
      "Navigasi bawah: Home · Murid · Catatan · Keuangan (4 item, turun dari 5)",
      "EvidenceCard di StudentDetail disederhanakan — hanya Avg Fokus + Nilai Rapor (tanpa Kepatuhan PR)",
      "AI suggest homework, notifikasi PR, template sesi PR, dan semua referensi homework dihapus",
    ],
  },
  {
    version: "v1.33.0",
    date: "2026-07-30",
    title: "Catat Sesi — Step Reorder, Quick Presets & IB DP Full Syllabus Topics",
    items: [
      "Step order baru: Jadwal → Materi → Kondisi → Detail → Catatan → Bukti — isi detail dulu, foto & TTD belakangan",
      "Bukti (foto & tanda tangan) bisa ditunda — tombol ⏭️ Nanti Saja di step akhir",
      "Quick presets ⚡ di step Kondisi (Lancar/Biasa/Kurang Fit/Reset) & Detail (Lancar/Butuh Latihan/Miskonsepsi) — isi 1 detik",
      "Engagement scoring lebih longgar & objektif — label Sangat Baik/Baik/Cukup/Kurang Fokus/Perlu Perhatian",
      "Materi step: tambah field 🎯 Fokus Utama untuk isi topik cepat",
      "IB Topics database restruktur: 600+ topik terorganisir per grade (MYP 1-5, DP, IGCSE) selaras textbook Haese & Harris",
      "11 IB DP subjects diperbarui ke full syllabus detail (Chemistry, Biology, Physics, Economics, Business, ESS, Geography, Math AA HL/SL, AI HL/SL) — ~500 subtopics",
      "Search & browse topik diprioritaskan berdasarkan grade siswa — topik cocok grade dapat +30 bonus score",
      "Mapping grade: Grade 6=MYP 1, Grade 7=MYP 2, Grade 8-9=MYP 3-4, Grade 10=MYP 5, Grade 11-12=DP",
    ],
  },
  {
    version: "v1.32.0",
    date: "2026-07-30",
    title: "Foto Bukti Pertemuan di Semua Layout + AI Ringkasan & Rencana Depan",
    items: [
      "Semua 27 layout kini menampilkan foto sesi (PhotoEl) — 10 layout yang sebelumnya tanpa foto kini lengkap",
      "Detail Sesi (DetailsEl: durasi, waktu, topik, mood) ditambahkan ke 9 layout yang belum memilikinya",
      "Cover page kini menampilkan galeri foto bukti pertemuan (maks 8 foto)",
      "Fix: counter kesiapan laporan kini menghitung shortNote sebagai narasi (tidak hanya narrative)",
      "AI Ringkasan kini juga generate Rencana Bulan Depan — satu klik untuk ringkasan + kutipan + rencana",
      "Tombol 🤖 Generate AI baru di section Fokus & Rencana — generate rencana depan via AI",
      "APP_VERSION kini dinamis dari package.json — update versi di satu tempat saja",
    ],
  },
  {
    version: "v1.31.0",
    date: "2026-07-30",
    title: "UX Audit Fixes — Kontras, Hierarki KPI, Navigasi & Aksesibilitas",
    items: [
      "Kontras teks: semua secondary text naik ke ≥4.5:1 (gray-400→600, slate-400→600) di 13 file — WCAG AA",
      "Command Center: Hari Ini jadi kartu full-width 32px + badge status eksplisit (✅⏳📋📅) + border kiri berwarna",
      "Command Center: Minggu Ini, Sesi Terlewat, Tindak Lanjut, Murid Aktif di-grid ulang dengan prioritas",
      "Progress bar ditebalkan ke 10-12px — lebih mudah dibaca dalam sekejap",
      "Header: tombol ⚙️ Settings & ⏻ Power kini 44×44px tap target + hover bg-gray-100",
      "BottomNav: tab aktif kini pakai pill bg-blue-50 + text-blue-700, min 48px touch target",
      "MetricCard: semua kartu kini punya left-border accent 4px + CTA klik langsung (Buka daftar / Lihat murid)",
      "Kalender Bulan/Minggu/Hari tetap utuh — hanya kontras panah navigasi yang ditingkatkan",
    ],
  },
  {
    version: "v1.30.0",
    date: "2026-07-30",
    title: "UX Audit — Home Screen & Monthly Report Overhaul",
    items: [
      "Home: gauge charts diganti KPI tiles + inline mini progress bar — lebih cepat dibaca",
      "Home: badge 'Perlu perhatian' → full-width alert strip dengan ⚠️ + count + tap-to-scroll ke inbox",
      "Home: MetricCard kini punya CTA action + trailing chevron — 'Buka daftar', 'Lihat murid'",
      "Home: tombol Catat jadi primary (blue filled), Keluar jadi ghost icon-only, tambah ⚙️ Settings di header",
      "BottomNav: 6→5 item, ikon emoji diganti SVG outline konsisten, Settings pindah ke header",
      "Kontras: semua teks secondary naik ke ≥4.5:1 — Gauge, ProgressBar, MetricCard, badge",
      "ProgressBar: tinggi bar dinaikkan (sm 4→8px, md 10→12px), teks detail lebih kontras",
      "MonthlyReport: 26 tema light-bg — token muted diperbaiki ke WCAG AA 4.5:1 (Lavender, Sakura, dll.)",
      "MonthlyReport: tema selector kini collapsible (default tertutup), preview melebar di desktop (max-w-2xl)",
      "MonthlyReport: filter subject chips (Semua + per-mapel) di atas daftar sesi",
    ],
  },
  {
    version: "v1.29.0",
    date: "2026-07-20",
    title: "UI/UX Overhaul — Touch Targets, Contrast, Loading States & Polish",
    items: [
      "Touch targets: semua tombol aksi kini ≥44px (Tugas, edit murid, panah kalender, tombol tutup modal, filter clear)",
      "Kontras teks: text-gray-300/400 → gray-500 di seluruh app — lolos WCAG AA (min 4.5:1)",
      "Font minimum: teks 8-9px → 10px di Gauge, Badge, BottomNav, dsb — lebih terbaca",
      "Loading states: 7 layar kini pakai Skeleton shimmer, bukan teks 'Memuat...' polos",
      "Hapus tombol 'Keluar' dari header Home — aksi destruktif jarang tidak perlu tempat utama",
      "Press feedback: semua tombol kini punya efek scale(0.97) saat ditekan (via CSS global)",
      "Settings Toast di-unify dengan ToastProvider global — tidak ada lagi toast duplikat",
      "Hapus ExitAppModal (dead code setelah tombol Keluar dihapus)",
    ],
  },
  {
    version: "v1.28.0",
    date: "2026-07-20",
    title: "Code Quality — Dead Code Removal, Deduplikasi, & Perbaikan Teknis",
    items: [
      "Hapus dead code: InvoiceCard.tsx & usePhotoCapture.ts (tidak pernah di-import)",
      "Deduplikasi addDaysToDate di CaptureSession → pakai addDays() dari lib/calendar.ts",
      "Deduplikasi toggleSubject → shared toggleArrayItem() di lib/arrays.ts (dipakai StudentForm & CaptureSession)",
      "Deduplikasi monthLabel di exportAbsensi.ts → impor dari lib/format.ts",
      "IA/EE logic dipisahkan dari paymentRepo.ts → iaeeRepo.ts sendiri",
      "useToast: fix memory leak — cleanup semua timer saat unmount + mounted guard",
      "A11y: tambah role='status' aria-live='polite' pada flash message di App.tsx",
    ],
  },
  {
    version: "v1.27.2",
    date: "2026-07-19",
    title: "Code Quality — Deduplikasi, Migrasi Settings, & Query Optimization",
    items: [
      "todayWIB() deduplikasi — satu sumber di lib/format.ts, repos impor dari situ (sebelumnya diduplikasi di helpers.ts)",
      "Migrasi settings (hash PIN, bank default) dipindahkan dari getSettings() ke initSettings() — dijalankan sekali saat startup, bukan setiap read",
      "getCashSummary kini pakai monthRange() menggantikan hardcode '-31' — akurat untuk semua bulan (Feb, bulan 30 hari)",
      "getMonthlyIncomeVsExpense kini 2 query besar (range scan) bukan N query kecil — konsisten dengan getCashSummary",
      "QuickExpenseModal didokumentasikan: sengaja tanpa PIN (write-only, tidak ekspos data sensitif)",
    ],
  },
  {
    version: "v1.27.1",
    date: "2026-07-19",
    title: "Keuangan Dipindahkan dari Dashboard + Sort Kalender Bulanan",
    items: [
      "Pendapatan harian & mingguan dipindahkan dari dashboard ke tab Ringkasan halaman Keuangan (💰) — semua info uang kini di satu tempat",
      "Tombol 💸 Catat di dashboard header — pencatatan pengeluaran cepat tanpa harus masuk PIN Keuangan",
      "Kalender bulanan kini mengurutkan sesi berdasarkan jam (paling awal di atas) — konsisten dengan tampilan mingguan & harian",
      "Backup/restore kini tervalidasi penuh, memakai snapshot konsisten, dan tetap kompatibel dengan file backup lama",
      "Kata sandi backup disembunyikan secara default; verifikasi backup Drive memeriksa struktur data secara penuh",
    ],
  },
  {
    version: "v1.27.0",
    date: "2026-07-17",
    title: "UI Overhaul — Dashboard, Analitik & Navigasi Baru",
    items: [
      "Dashboard Home baru: gauge sesi, bar chart mingguan, progress bar, & glance pendapatan harian/mingguan",
      "Inbox Perlu Perhatian kini tabbed (Sesi | PR Telat | PR Segera | Follow-up) dengan badge count",
      "Halaman Analitik baru (📊) — 3 tab: Keuangan (grafik batang, tren, donat pengeluaran, forecast), Murid (kontribusi pendapatan, engagement), Operasional (gauge, no-show rate, PR completion)",
      "Breadcrumb otomatis di semua halaman dalam (Murid, Catat Sesi, Tugas, Laporan, Keuangan)",
      "Detail Murid kini pakai tab (Ringkasan | Sesi & Jadwal | Nilai | IA/EE)",
      "RatingIndicator visual (dot/star/bar) menggantikan angka mentah engagement",
      "Skeleton loader shimmer — pengganti teks 'Memuat...' di semua halaman",
      "12 komponen UI baru murni SVG/Tailwind: BarChart, LineChart, DonutChart, Gauge, ProgressBar, RatingIndicator, Badge, Popover, Breadcrumb, Tabs, Skeleton — tanpa dependensi tambahan",
    ],
  },
  {
    version: "v1.26.2",
    date: "2026-07-11",
    title: "Patch — Review Visual 26 Layout Laporan",
    items: [
      "Semua 26 layout dirender dengan data bulan penuh & diperiksa visual satu per satu",
      "Grid 2× kembali 4 sesi/halaman (6 membuat halaman terlalu panjang — 3 baris foto)",
      "Rapor Style 10/hal, Compact 8/hal, Jurnal 6/hal terverifikasi nyaman dibaca",
      "Seed data dev: seedDummy(true) kini membersihkan data lama (tidak menduplikasi murid)",
      "Tool review layout baru: e2e/layout-review.spec.ts — screenshot semua layout sekali jalan",
    ],
  },
  {
    version: "v1.26.1",
    date: "2026-07-10",
    title: "Patch — Audit UI/UX Menyeluruh",
    items: [
      "Banner backup mingguan pindah ke bawah — tidak lagi menutupi judul halaman & form (di Laporan sempat menutup pilihan murid/bulan)",
      "Banner tidak lagi menghalangi tombol modal (update modal, konfirmasi, dll.)",
      "Grafik Engagement di Detail Murid kini benar-benar tampil (bar sempat 0px — tak terlihat)",
      "Riwayat Sesi default 'Semua bulan' — sebelumnya tampak kosong padahal ada sesi (filter diam-diam terkunci di bulan berjalan)",
      "Empty state Riwayat Sesi kontekstual: 'Tidak ada sesi di [bulan]' + tombol Tampilkan Semua",
      "Screenshot katalog laporan kini berisi data (sebelumnya kosong — bahan iklan Instagram)",
    ],
  },
  {
    version: "v1.26.0",
    date: "2026-07-10",
    title: "Laporan Kronologis + Halaman Lebih Padat",
    items: [
      "Urutan sesi di laporan kini KRONOLOGIS (awal→akhir bulan) — orang tua membaca sebagai cerita perkembangan",
      "Semua grafik tren (Sparkline Fokus, Pertumbuhan, Perbandingan) otomatis searah waktu",
      "Paginasi cerdas per layout: Rapor Style 10 sesi/halaman, Compact/Minimalis/Bullet/Checklist 8, layout foto besar tetap 4",
      "Laporan bulan padat kini butuh lebih sedikit halaman saat dikirim via WA",
    ],
  },
  {
    version: "v1.25.0",
    date: "2026-07-10",
    title: "Narasi AI + Export Lebih Setia Desain",
    items: [
      "BARU: tombol 📖 Narasi AI — tulis narasi 40–60 kata untuk SEMUA sesi sekaligus dari shortNote, plus ringkasan, catatan guru & kutipan (bisa di-Undo penuh)",
      "Poles AI dinamai ulang jadi ✨ Ringkasan AI (ringkasan + kutipan saja, lebih murah)",
      "Export JPG/PNG/PDF kini membawa font tema (Pacifico, Caveat, dll.) — sebelumnya jatuh ke font default",
      "Label laporan otomatis pakai teks gelap di warna palet terang (Neon/Retro kini terbaca)",
      "Foto gaya 'vintage' kini benar-benar ber-efek sepia (CSS-nya sempat invalid)",
      "Layout Per Mapel: 'avg 0/10' disembunyikan bila sesi tak punya skor engagement",
      "E2E test baru: buat laporan → export JPG diverifikasi menghasilkan file",
    ],
  },
  {
    version: "v1.24.2",
    date: "2026-07-10",
    title: "Patch — Perbaikan Laporan Bulanan",
    items: [
      "Layout 'Per Minggu': grup mingguan tidak lagi tampil 'Minggu NaN'",
      "Layout 'Jurnal': angka besar kini nomor tanggal, bukan tahun",
      "Layout 'Perbandingan': arah tren Awal vs Akhir bulan dikoreksi (sempat terbalik)",
      "Grafik 'Tren Fokus' & 'Pertumbuhan': sumbu waktu kini kronologis kiri→kanan",
      "KPI Dashboard/Ringkasan/Analitik: pakai total sebulan penuh, bukan per halaman",
      "Kolom tanggal di Rapor Style/Snapshot: '5 Juni', bukan '2026'",
      "Mode Bandingkan: tema kustom kini ter-render benar",
      "Teks fallback narasi dinetralkan (tidak ada lagi instruksi tutor di laporan ortu)",
    ],
  },
  {
    version: "v1.24.1",
    date: "2026-07-16",
    title: "Patch — Bug Fixes & Polish",
    items: [
      "Update modal — tampil saat versi baru, lengkap dengan changelog per rilis",
      "Perbaikan label jadwal seri: \"Di hari yang sama setiap minggu\"",
      "Fix form edit jadwal dari Calendar agar tidak ter-reset saat buka",
      "JPG export sekarang per halaman (tidak digabung jadi 1 gambar panjang)",
      "AI narasi laporan: prompt diperkuat dengan contoh spesifik",
      "Teks billing WA: tanpa heading 'Pembayaran' atau 'Transfer ke'",
      "Font size tombol calendar diperbesar biar legible di HP",
      "Perbaikan urutan sesi di laporan (terbaru di atas)",
    ],
  },
  {
    version: "v1.24.0",
    date: "2026-07-16",
    title: "AI Lebih Pintar + Foto & Laporan Lebih Rapi",
    items: [
      "AI prompt diperkuat — narasi tetap jaga fakta shortNote, tidak menghapus isi catatan tutor",
      "AI analisis siswa lebih tajam — rekomendasi fokus sesi berikutnya lebih spesifik",
      "AI saran PR lebih konkret — langsung bisa dikerjakan, bukan cuma judul topik",
      "AI draft catatan sesi lebih terstruktur — ada contoh output di prompt",
      "AI pengingat bayaran lebih sopan — nada ringan, tidak seperti nagih",
      "Kompresi foto lebih kecil — 640px, kualitas optimal untuk tampil di laporan",
      "Export JPG per halaman — tidak lagi digabung jadi satu gambar panjang",
      "Laporan urut dari sesi terbaru ke terlama",
      "Galeri: bisa pilih foto dari gallery HP selain kamera langsung",
      "Bank account default: BCA, CIMB, BRI otomatis terisi",
      "Tagihan WA: tanpa kata 'Transfer ke' atau 'Pembayaran', lebih ringan",
      "Tanggal sesi: tidak ada lagi batas 14 hari ke belakang",
      "Tampilan laporan: perbaikan overlap konten antar halaman",
    ],
  },
];
